{
 "title": "Ökofen",
 "description": "Pellematic Smart",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Zustände",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Starts gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_starts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pe1" }
     ]
    },
    {
     "alias": "Laufzeit gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_runtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pe1" }
     ]
    },
    {
     "alias": "Laufzeit Durchschnitt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_avg_runtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pe1" }
     ]
    },
    {
     "alias": "Einmal WW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "ww1_L_pump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "ww1" }
     ]
    },
    {
     "alias": "HK1 Pumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk1_L_pump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk1" }
     ]
    },
    {
     "alias": "HK2 Pumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk2_L_pump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk2" }
     ]
    },
    {
     "alias": "PU1 Pumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_pump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pu1" }
     ]
    },
    {
     "alias": "WW1 Pumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "ww1_L_pump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "ww1" }
     ]
    },
    {
     "alias": "SK1 Pumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "sk1_L_pump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "sk1" }
     ]
    },
    {
     "alias": "Aussentemp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "system_L_ambient" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "system" }
     ]
    }
   ]
  },
  {
   "title": "Heizkreis 1 / Fussbodenheizung",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk1_L_flowtemp_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk1" }
     ]
    },
    {
     "alias": "Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk1_L_flowtemp_set" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk1" }
     ]
    }
   ]
  },
  {
   "title": "Leistungsdaten Brenner",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "alias": "PE1 Pellematic Brenner",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_statetext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HK1 Heizkreis 1 Fussboden",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk1_L_statetext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HK2 Heizkreis 2 Heizkörper",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk2_L_statetext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PU1 Pufferspeicher",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_statetext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "WW1 Warmwasser",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "ww1_L_statetext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "SK1 Solarkollektor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "sk1_L_statetext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heizkreis 2 / Heizkörper",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk2_L_flowtemp_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk2" }
     ]
    },
    {
     "alias": "Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "hk2_L_flowtemp_set" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk2" }
     ]
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_tpo_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pu1" }
     ]
    }
   ]
  },
  {
   "title": "Modulation Brenner",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Modulation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pe1" }
     ]
    }
   ]
  },
  {
   "title": "Solar-Durchfluss",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Flow",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "se1_L_flow" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "se1" }
     ]
    }
   ]
  },
  {
   "title": "Solar-Leistung",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ertrag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "se1_L_pwr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "se1" }
     ]
    }
   ]
  },
  {
   "title": "Solaranlage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Kollektor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "sk1_L_koll_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "SPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "sk1_L_spu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soll-Ist-Puffer",
   "type": "timeseries",
   "description": "wo kommen die Anforderungen her ?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "TPM-Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_tpm_set" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "TPM-Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_tpm_act" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TPO-Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_tpo_set" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "TPO-Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pu1_L_tpo_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "WW-Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "ww1_L_temp_set" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leistung Modulation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Modulation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pe1" }
     ]
    },
    {
     "alias": "FeuerraumTemp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "pe1_L_frt_temp_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "pe1" }
     ]
    }
   ]
  },
  {
   "title": "Laufzeit im selektierten Zeitraum",
   "type": "stat",
   "description": "Minuten mit Modulation >10 zählen und in 4min-Blöcken addieren.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Brennerlaufzeit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT non_negative_derivative(count(\"pe1_L_modulation\"), 1m) *4 FROM \"oekofen\" WHERE \"pe1_L_modulation\" >10 AND  $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "*4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "verbrauchte Pellets",
   "type": "stat",
   "description": "Laufzeit in h * 7.8kW / 4.9kg/kW Brennwert (1.6)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Pelletsverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT non_negative_derivative(count(\"pe1_L_modulation\"), 1m) *4/60*7.8/4.9 FROM \"oekofen\" WHERE \"pe1_L_modulation\" >10 AND  $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "*4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2 Ausstoss im sel. Zeitraum",
   "type": "stat",
   "description": "Laufzeit in Stunden * 7.8kW * 9g/kWh (SIR 2007)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "CO2-Ausstoss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT non_negative_derivative(count(\"pe1_L_modulation\"), 1m) *4/60 * 7.8 * 9  FROM \"oekofen\" WHERE \"pe1_L_modulation\" >10 AND  $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "*4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Feinstaub im sel. Zeitraum",
   "type": "stat",
   "description": "Laufzeit h * 7.8kW * 0.05g/kWh",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Brennerlaufzeit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT non_negative_derivative(count(\"pe1_L_modulation\"), 1m) *4/60*7.8*0.05 FROM \"oekofen\" WHERE \"pe1_L_modulation\" >10 AND  $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "*4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solarleistung der letzten 14 Tage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "kwatth", "label": "pro Tag" }
   ],
   "targets": [
    {
     "alias": "Leistung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT max(\"se1_L_day\") FROM \"km4\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "se1_L_day" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "= Wegstrecke mit VW Up 1.0 Ecofuel (84gCO2/km)",
   "type": "stat",
   "description": "Laufzeit h *7.8kW * 25g/kWh / 84g/km",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Wegstrecke",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT non_negative_derivative(count(\"pe1_L_modulation\"), 1m) *4/60 * 7.8 * 9 / 84 FROM \"oekofen\" WHERE \"pe1_L_modulation\" >10 AND  $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "*4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kosten im Zeitraum",
   "type": "stat",
   "description": "Laufzeit h * 7.8kW / 4.9kg/kW * €213€/tonne",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Kosten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "heizung",
     "query": "SELECT non_negative_derivative(count(\"pe1_L_modulation\"), 1m) *4/60 * 7.8 / 4.9 * 0.213 FROM \"oekofen\" WHERE \"pe1_L_modulation\" >10 AND  $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "pe1_L_modulation" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "*4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solarertrag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Ertrag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "se1_L_pwr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "se1" }
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Wetterinfo",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "akt Temperatur",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "weather_L_temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "weather" }
     ]
    },
    {
     "alias": "akt Wolkendecke in %",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "weather_L_clouds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "weather" }
     ]
    },
    {
     "alias": "kommende Temperatur",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "weather_L_forecast_temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "weather" }
     ]
    },
    {
     "alias": "kommende Wolkendecke in %",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "weather_L_forecast_clouds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "weather" }
     ]
    },
    {
     "alias": "Sonnenaufgang",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "weather_L_starttime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "weather" }
     ]
    },
    {
     "alias": "Sonnenuntergang",
     "measurement": "oekofen",
     "select": [
      [
       { "params": [ "weather_L_endtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "weather" }
     ]
    }
   ]
  }
 ]
}